# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: fastify
      MYSQL_PASSWORD: fastify
      MYSQL_DATABASE: fastify
    ports:
      - 3306:3306
    security_opt:
      - seccomp:unconfined

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
