apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_USER
              value: fastify
            - name: MYSQL_PASSWORD
              value: fastify
            - name: MYSQL_DATABASE
              value: fastify
---
apiVersion: v1
kind: Service
metadata:
  name: fastify-mysql-srv
spec:
  selector:
    app: mysql
  ports:
    - name: db
      protocol: TCP
      port: 3306
      targetPort: 3306
